const FETCH_PLANTS_REQUEST = "FETCH_PLANTS_REQUEST";
const FETCH_PLANTS_SUCCESS = "FETCH_PLANTS_SUCCESS";
const FETCH_PLANTS_FAIL = "FETCH_PLANTS_FAIL";

export { FETCH_PLANTS_REQUEST, FETCH_PLANTS_SUCCESS, FETCH_PLANTS_FAIL };
